const nodemailer = require('nodemailer');
const otpGenerator = require('otp-generator');

const generateOTP = () => {
  return otpGenerator.generate(6, { upperCase: false, specialChars: false });
};

// const sendOTPEmail = async (email, otp, name) => {
//   const transporter = nodemailer.createTransport({
//     service: 'gmail',
//     auth: {
//       user: process.env.EMAIL_USER,
//       pass: process.env.EMAIL_PASS,
//     },
//   });

//   const mailOptions = {
//     from: process.env.EMAIL_USER,
//     to: email,
//     subject: 'OTP For OnlyMobiles User Registeration',
//     html: `  <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
//         <h2 style="color: #333;">Hello ${name},</h2>
//         <p style="font-size: 16px;">Your OTP for registration is:</p>
//         <h1 style="background: #f4f4f4; padding: 10px; display: inline-block; border-radius: 5px;">${otp}</h1>
//         <p style="font-size: 14px; color: #888;">This OTP is valid for <strong>5 minutes</strong>.</p>
//         <br>
//         <p style = "font-size: 14px; color: #333;">This Email is autogenerated. Please Do Not Reply to this Email.</p>
//         <p>Regards,</p>
//         <p><strong>OnlyMobiles Team</strong></p>
//         <hr>
//         <p style="font-size: 12px; color: #666;">Powered by <strong>DDMailer</strong></p>
//       </div>`,
//   };

//   await transporter.sendMail(mailOptions);
// };

const sendOTPEmail = async (email, otp, name) => {
  try {
    const transporter = nodemailer.createTransport({
      host: 'smtp.gmail.com',
      port: 465,
      secure: true,
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
      connectionTimeout: 10000,
      greetingTimeout: 10000,
      socketTimeout: 10000,
    });

    const mailOptions = {
      from: process.env.EMAIL_USER,
      to: email,
      subject: 'OTP For OnlyMobiles User Registeration',
      html: `  <div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
        <h2 style="color: #333;">Hello ${name},</h2>
        <p style="font-size: 16px;">Your OTP for registration is:</p>
        <h1 style="background: #f4f4f4; padding: 10px; display: inline-block; border-radius: 5px;">${otp}</h1>
        <p style="font-size: 14px; color: #888;">This OTP is valid for <strong>5 minutes</strong>.</p>
        <br>
        <p style = "font-size: 14px; color: #333;">This Email is autogenerated. Please Do Not Reply to this Email.</p>
        <p>Regards,</p>
        <p><strong>OnlyMobiles Team</strong></p>
        <hr>
        <p style="font-size: 12px; color: #666;">Powered by <strong>DDMailer</strong></p>
      </div>`,
    };

    await transporter.sendMail(mailOptions);
  } catch (err) {
    console.error('Email error:', err);
    throw err; // IMPORTANT: so API doesn't hang
  }
};
module.exports = { generateOTP, sendOTPEmail };
